### ISSUE TITLE
[bug] Should not list emails upon pinging

### ISSUE THREAD

**Issue by axic** [alita-moore/EIP-Bot#9]
Example from here https://github.com/ethereum/EIPs/pull/3768#issuecomment-906099599:

![Screenshot](https://user-images.githubusercontent.com/20340/130933342-75e9ee6c-3dbf-4772-b905-63493b359bd9.png)

Some old EIPs have email addresses as opposed to github username, those should be ignored during printing I think. There used to be a way to look up a github username based on an email and that is what the old bot did. If it did found a user, that was pinged.

**Comment by alita-moore** [comment]
@axic there are ways for me to search users / I can try to get that functionality back up and running. It's easier to just not include it, though.

**Comment by alita-moore** [comment]
also @axic some of these still work, for example on this pull request https://github.com/ethereum/EIPs/pull/3767 greg's email resolves to the correct github username
